services : 
 vendeur : 
  git_url : https : //github.com/cloud66 - samples/acme.git
   git_branch : master
   dockerfile_path :  "./Dockerfile" 
  build_root : vendeur
  acheteur : 
  git_url : https : //github.com/cloud66 - samples/ acme.git
   git_branch : master
   dockerfile_path :  "./Dockerfile" 
  build_root : acheteur
